# Generated by Django 5.2.9 on 2026-03-06 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdiagApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='collection_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=50, null=True)),
                ('lab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EdiagApp.labreg')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EdiagApp.login')),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EdiagApp.collector'),
        ),
    ]
