# Generated by Django 5.2.9 on 2026-03-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdiagApp', '0002_bookings_collection_status_collector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='labreg',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userreg',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
